#---------------------------------
# General Site Settings

title: 维信金科
description: 维信金科，让金融触手可及

#---------------------------------
# Header Menu List
nav-menus:
- {text: 'About Me', url: '#about'}
- {text: 'Work', url: '#work'}
- {text: 'Client', url: '#client'}
- {text: 'Contact', url: '#contact'}

#---------------------------------
# Skill Section
skills:
- {name: 'Communication', level: 8}
- {name: 'Organization', level: 6}
- {name: 'Learning', level: 9}
- {name: 'Teaching', level: 5}
- {name: 'Planning', level: 7}
- {name: 'Visual Design', level: 8}
- {name: 'UX Design', level: 10}
- {name: 'Programming', level: 8}
